
repairparts = {
	weight = 20,
	shouldClose = "true",
	image = "repairparts.png",
	name = "repairparts",
	type = "item",
	label = "Repair Engine Parts",
	useable = "true",
  },

ultimate_block = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_block.png",
	name = "ultimate_block",
	type = "item",
	label = "Ultimate Block",
	useable = "true",
  },
 tcs = {
	weight = 20,
	shouldClose = "true",
	image = "tcs.png",
	name = "tcs",
	type = "item",
	label = "Traction Control System (TCS)",
	useable = "true",
  },
 elite_fuelinjector = {
	weight = 20,
	shouldClose = "true",
	image = "elite_fuelinjector.png",
	name = "elite_fuelinjector",
	type = "item",
	label = "Elite Fuel Injectors",
	useable = "true",
  },
 axletorsionfront = {
	weight = 20,
	shouldClose = "true",
	image = "axletorsionfront.png",
	name = "axletorsionfront",
	type = "item",
	label = "Axle Torsion (Front)",
	useable = "true",
  },
 engine_sparkplug = {
	weight = 20,
	shouldClose = "true",
	image = "engine_sparkplug.png",
	name = "engine_sparkplug",
	type = "item",
	label = "Sparkplugs Kit",
	useable = "true",
  },
 elite_crankshaft = {
	weight = 20,
	shouldClose = "true",
	image = "elite_crankshaft.png",
	name = "elite_crankshaft",
	type = "item",
	label = "Elite CrankShaft",
	useable = "true",
  },
 engine_gasket = {
	weight = 20,
	shouldClose = "true",
	image = "engine_gasket.png",
	name = "engine_gasket",
	type = "item",
	label = "OEM Head Gasket Kit",
	useable = "true",
  },
 elite_flywheel = {
	weight = 20,
	shouldClose = "true",
	image = "elite_flywheel.png",
	name = "elite_flywheel",
	type = "item",
	label = "Elite Flywheel",
	useable = "true",
  },
 kers = {
	weight = 20,
	shouldClose = "true",
	image = "kers.png",
	name = "kers",
	type = "item",
	label = "Kinetic Energy Recovery System (KERS)",
	useable = "true",
  },
 aluminum = {
	weight = 20,
	shouldClose = "true",
	image = "aluminum.png",
	name = "aluminum",
	type = "item",
	label = "aluminum",
	useable = "true",
  },
 drag_tires = {
	weight = 20,
	shouldClose = "true",
	image = "drag_tires.png",
	name = "drag_tires",
	type = "item",
	label = "Drag Tires",
	useable = "true",
  },
 racing_gearbox = {
	weight = 20,
	shouldClose = "true",
	image = "racing_gearbox.png",
	name = "racing_gearbox",
	type = "item",
	label = "Racing Gear Box",
	useable = "true",
  },
 methane = {
	weight = 20,
	shouldClose = "true",
	image = "methane.png",
	name = "methane",
	type = "item",
	label = "Methane",
	useable = "true",
  },
 cvttranny = {
	weight = 20,
	shouldClose = "true",
	image = "cvttranny.png",
	name = "cvttranny",
	type = "item",
	label = "CVT Transmission",
	useable = "true",
  },
 axletorsionrear = {
	weight = 20,
	shouldClose = "true",
	image = "axletorsionrear.png",
	name = "axletorsionrear",
	type = "item",
	label = "Axle Torsion (Rear)",
	useable = "true",
  },
 pro_camshaft = {
	weight = 20,
	shouldClose = "true",
	image = "pro_camshaft.png",
	name = "pro_camshaft",
	type = "item",
	label = "Pro Camshaft",
	useable = "true",
  },
 elite_camshaft = {
	weight = 20,
	shouldClose = "true",
	image = "elite_camshaft.png",
	name = "elite_camshaft",
	type = "item",
	label = "Elite Camshaft",
	useable = "true",
  },
 pro_flywheel = {
	weight = 20,
	shouldClose = "true",
	image = "pro_flywheel.png",
	name = "pro_flywheel",
	type = "item",
	label = "Pro Flywheel",
	useable = "true",
  },
 elite_clutch = {
	weight = 20,
	shouldClose = "true",
	image = "elite_clutch.png",
	name = "elite_clutch",
	type = "item",
	label = "Elite Transmission Clutch",
	useable = "true",
  },
 racing_gasket = {
	weight = 20,
	shouldClose = "true",
	image = "racing_gasket.png",
	name = "racing_gasket",
	type = "item",
	label = "Racing Head Gasket Kit",
	useable = "true",
  },
 pro_gasket = {
	weight = 20,
	shouldClose = "true",
	image = "pro_gasket.png",
	name = "pro_gasket",
	type = "item",
	label = "Pro Head Gasket Kit",
	useable = "true",
  },
 oem_brakes = {
	weight = 20,
	shouldClose = "true",
	image = "oem_brakes.png",
	name = "oem_brakes",
	type = "item",
	label = "OEM Brakes",
	useable = "true",
  },
 ecu = {
	weight = 20,
	shouldClose = "true",
	image = "ecu.png",
	name = "ecu",
	type = "item",
	label = "ecu",
	useable = "true",
  },
 racing_airfilter = {
	weight = 20,
	shouldClose = "true",
	image = "racing_airfilter.png",
	name = "racing_airfilter",
	type = "item",
	label = "Racing Intake Air Filter",
	useable = "true",
  },
 ultimate_connectingrods = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_connectingrods.png",
	name = "ultimate_connectingrods",
	type = "item",
	label = "Ultimate Connecting Rods Kit",
	useable = "true",
  },
 engine_connectingrods = {
	weight = 20,
	shouldClose = "true",
	image = "engine_connectingrods.png",
	name = "engine_connectingrods",
	type = "item",
	label = "OEM Connecting Rods Kit",
	useable = "true",
  },
 racing_brakes = {
	weight = 20,
	shouldClose = "true",
	image = "racing_brakes.png",
	name = "racing_brakes",
	type = "item",
	label = "Racing Brakes",
	useable = "true",
  },
 ultimate_clutch = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_clutch.png",
	name = "ultimate_clutch",
	type = "item",
	label = "Ultimate Transmission Clutch",
	useable = "true",
  },
 pro_connectingrods = {
	weight = 20,
	shouldClose = "true",
	image = "pro_connectingrods.png",
	name = "pro_connectingrods",
	type = "item",
	label = "Pro Connecting Rods Kit",
	useable = "true",
  },
 ultimate_oil = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_oil.png",
	name = "ultimate_oil",
	type = "item",
	label = "Ultimate Oil",
	useable = "true",
  },
 racing_pistons = {
	weight = 20,
	shouldClose = "true",
	image = "racing_pistons.png",
	name = "racing_pistons",
	type = "item",
	label = "Racing Pistons Kit",
	useable = "true",
  },
 ultimate_gasket = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_gasket.png",
	name = "ultimate_gasket",
	type = "item",
	label = "Ultimate Head Gasket Kit",
	useable = "true",
  },
 ultimate_brakes = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_brakes.png",
	name = "ultimate_brakes",
	type = "item",
	label = "Ultimate Brakes",
	useable = "true",
  },
 offroadtune2 = {
	weight = 20,
	shouldClose = "true",
	image = "offroadtune2.png",
	name = "offroadtune2",
	type = "item",
	label = "Offroad Tune 2",
	useable = "true",
  },
 sports_tires = {
	weight = 20,
	shouldClose = "true",
	image = "sports_tires.png",
	name = "sports_tires",
	type = "item",
	label = "Sports Tires",
	useable = "true",
  },
 stanced = {
	weight = 20,
	shouldClose = "true",
	image = "stanced.png",
	name = "stanced",
	type = "item",
	label = "Stanced Tune",
	useable = "true",
  },
 elite_gasket = {
	weight = 20,
	shouldClose = "true",
	image = "elite_gasket.png",
	name = "elite_gasket",
	type = "item",
	label = "Elite Head Gasket Kit",
	useable = "true",
  },
 engine_pistons = {
	weight = 20,
	shouldClose = "true",
	image = "engine_pistons.png",
	name = "engine_pistons",
	type = "item",
	label = "OEM Pistons Kit",
	useable = "true",
  },
 axlesolidfront = {
	weight = 20,
	shouldClose = "true",
	image = "axlesolidfront.png",
	name = "axlesolidfront",
	type = "item",
	label = "Axle Solid (Front)",
	useable = "true",
  },
 ultimate_camshaft = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_camshaft.png",
	name = "ultimate_camshaft",
	type = "item",
	label = "Ultimate Camshaft",
	useable = "true",
  },
 elite_brakes = {
	weight = 20,
	shouldClose = "true",
	image = "elite_brakes.png",
	name = "elite_brakes",
	type = "item",
	label = "Elite Brakes",
	useable = "true",
  },
 ultimate_fuelinjector = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_fuelinjector.png",
	name = "ultimate_fuelinjector",
	type = "item",
	label = "Ultimate Fuel Injectors",
	useable = "true",
  },
 engine_airfilter = {
	weight = 20,
	shouldClose = "true",
	image = "engine_airfilter.png",
	name = "engine_airfilter",
	type = "item",
	label = "OEM Intake Air Filter",
	useable = "true",
  },
 iron = {
	weight = 20,
	shouldClose = "true",
	image = "iron.png",
	name = "iron",
	type = "item",
	label = "iron",
	useable = "true",
  },
 pro_valves = {
	weight = 20,
	shouldClose = "true",
	image = "pro_valves.png",
	name = "pro_valves",
	type = "item",
	label = "Pro Head Valves Kit",
	useable = "true",
  },
 rearwheeldrive = {
	weight = 20,
	shouldClose = "true",
	image = "rearwheeldrive.png",
	name = "rearwheeldrive",
	type = "item",
	label = "Rear Wheel Drivetrain",
	useable = "true",
  },
 ultimate_valves = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_valves.png",
	name = "ultimate_valves",
	type = "item",
	label = "Ultimate Head Valves Kit",
	useable = "true",
  },
 engine_valves = {
	weight = 20,
	shouldClose = "true",
	image = "engine_valves.png",
	name = "engine_valves",
	type = "item",
	label = "OEM Head Valves Kit",
	useable = "true",
  },
 elite_sparkplug = {
	weight = 20,
	shouldClose = "true",
	image = "elite_sparkplug.png",
	name = "elite_sparkplug",
	type = "item",
	label = "Elite Sparkplugs Kit",
	useable = "true",
  },
 ultimate_airfilter = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_airfilter.png",
	name = "ultimate_airfilter",
	type = "item",
	label = "Ultimate Intake Air Filter",
	useable = "true",
  },
 ultimate_flywheel = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_flywheel.png",
	name = "ultimate_flywheel",
	type = "item",
	label = "Ultimate Flywheel",
	useable = "true",
  },
 engine_crankshaft = {
	weight = 20,
	shouldClose = "true",
	image = "engine_crankshaft.png",
	name = "engine_crankshaft",
	type = "item",
	label = "OEM CrankShaft",
	useable = "true",
  },
 elite_block = {
	weight = 20,
	shouldClose = "true",
	image = "elite_block.png",
	name = "elite_block",
	type = "item",
	label = "Elite Block",
	useable = "true",
  },
 offroadtune1 = {
	weight = 20,
	shouldClose = "true",
	image = "offroadtune1.png",
	name = "offroadtune1",
	type = "item",
	label = "Offroad Tune 1",
	useable = "true",
  },
 pro_clutch = {
	weight = 20,
	shouldClose = "true",
	image = "pro_clutch.png",
	name = "pro_clutch",
	type = "item",
	label = "Pro Transmission Clutch",
	useable = "true",
  },
 ultimate_pistons = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_pistons.png",
	name = "ultimate_pistons",
	type = "item",
	label = "Ultimate Pistons Kit",
	useable = "true",
  },
 transmition_clutch = {
	weight = 20,
	shouldClose = "true",
	image = "transmition_clutch.png",
	name = "transmition_clutch",
	type = "item",
	label = "OEM Transmission Clutch",
	useable = "true",
  },
 racing_crankshaft = {
	weight = 20,
	shouldClose = "true",
	image = "racing_crankshaft.png",
	name = "racing_crankshaft",
	type = "item",
	label = "Racing CrankShaft",
	useable = "true",
  },
 lsdr = {
	weight = 20,
	shouldClose = "true",
	image = "lsdr.png",
	name = "lsdr",
	type = "item",
	label = "Limited Slip Differential (Rear)",
	useable = "true",
  },
 copper = {
	weight = 20,
	shouldClose = "true",
	image = "copper.png",
	name = "copper",
	type = "item",
	label = "copper",
	useable = "true",
  },
 elite_oil = {
	weight = 20,
	shouldClose = "true",
	image = "elite_oil.png",
	name = "elite_oil",
	type = "item",
	label = "Elite Oil",
	useable = "true",
  },
 racing_flywheel = {
	weight = 20,
	shouldClose = "true",
	image = "racing_flywheel.png",
	name = "racing_flywheel",
	type = "item",
	label = "Racing Flywheel",
	useable = "true",
  },
 allwheeldrive = {
	weight = 20,
	shouldClose = "true",
	image = "allwheeldrive.png",
	name = "allwheeldrive",
	type = "item",
	label = "All Wheel Drivetrain",
	useable = "true",
  },
 elite_suspension = {
	weight = 20,
	shouldClose = "true",
	image = "elite_suspension.png",
	name = "elite_suspension",
	type = "item",
	label = "Elite Suspension",
	useable = "true",
  },
 racing_camshaft = {
	weight = 20,
	shouldClose = "true",
	image = "racing_camshaft.png",
	name = "racing_camshaft",
	type = "item",
	label = "Racing Camshaft",
	useable = "true",
  },
 lsdf = {
	weight = 20,
	shouldClose = "true",
	image = "lsdf.png",
	name = "lsdf",
	type = "item",
	label = "Limited Slip Differential (Front)",
	useable = "true",
  },
 oem_gearbox = {
	weight = 20,
	shouldClose = "true",
	image = "oem_gearbox.png",
	name = "oem_gearbox",
	type = "item",
	label = "OEM Gear Box",
	useable = "true",
  },
 pro_gearbox = {
	weight = 20,
	shouldClose = "true",
	image = "pro_gearbox.png",
	name = "pro_gearbox",
	type = "item",
	label = "Pro Gear Box",
	useable = "true",
  },
 elite_connectingrods = {
	weight = 20,
	shouldClose = "true",
	image = "elite_connectingrods.png",
	name = "elite_connectingrods",
	type = "item",
	label = "Elite Connecting Rods Kit",
	useable = "true",
  },
 racing_clutch = {
	weight = 20,
	shouldClose = "true",
	image = "racing_clutch.png",
	name = "racing_clutch",
	type = "item",
	label = "Racing Transmission Clutch",
	useable = "true",
  },
 racing_suspension = {
	weight = 20,
	shouldClose = "true",
	image = "racing_suspension.png",
	name = "racing_suspension",
	type = "item",
	label = "Racing Suspension",
	useable = "true",
  },
 ultimate_sparkplug = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_sparkplug.png",
	name = "ultimate_sparkplug",
	type = "item",
	label = "Ultimate Sparkplugs Kit",
	useable = "true",
  },
 pro_airfilter = {
	weight = 20,
	shouldClose = "true",
	image = "pro_airfilter.png",
	name = "pro_airfilter",
	type = "item",
	label = "Pro Intake Air Filter",
	useable = "true",
  },
 racing_tires = {
	weight = 20,
	shouldClose = "true",
	image = "racing_tires.png",
	name = "racing_tires",
	type = "item",
	label = "Racing Tires",
	useable = "true",
  },
 elite_pistons = {
	weight = 20,
	shouldClose = "true",
	image = "elite_pistons.png",
	name = "elite_pistons",
	type = "item",
	label = "Elite Pistons Kit",
	useable = "true",
  },
 pro_pistons = {
	weight = 20,
	shouldClose = "true",
	image = "pro_pistons.png",
	name = "pro_pistons",
	type = "item",
	label = "Pro Pistons Kit",
	useable = "true",
  },
 pro_fuelinjector = {
	weight = 20,
	shouldClose = "true",
	image = "pro_fuelinjector.png",
	name = "pro_fuelinjector",
	type = "item",
	label = "Pro Fuel Injectors",
	useable = "true",
  },
 drift_tires = {
	weight = 20,
	shouldClose = "true",
	image = "drift_tires.png",
	name = "drift_tires",
	type = "item",
	label = "Drift Tires",
	useable = "true",
  },
 axlesolidrear = {
	weight = 20,
	shouldClose = "true",
	image = "axlesolidrear.png",
	name = "axlesolidrear",
	type = "item",
	label = "Axle Solid (Rear)",
	useable = "true",
  },
 pro_oil = {
	weight = 20,
	shouldClose = "true",
	image = "pro_oil.png",
	name = "pro_oil",
	type = "item",
	label = "Pro Oil",
	useable = "true",
  },
 rubber = {
	weight = 20,
	shouldClose = "true",
	image = "rubber.png",
	name = "rubber",
	type = "item",
	label = "Rubber",
	useable = "true",
  },
 engine_flywheel = {
	weight = 20,
	shouldClose = "true",
	image = "engine_flywheel.png",
	name = "engine_flywheel",
	type = "item",
	label = "OEM Flywheel",
	useable = "true",
  },
 engine_fuelinjector = {
	weight = 20,
	shouldClose = "true",
	image = "engine_fuelinjector.png",
	name = "engine_fuelinjector",
	type = "item",
	label = "OEM Fuel Injectors",
	useable = "true",
  },
 frontwheeldrive = {
	weight = 20,
	shouldClose = "true",
	image = "frontwheeldrive.png",
	name = "frontwheeldrive",
	type = "item",
	label = "Front Wheel Drivetrain",
	useable = "true",
  },
 elite_gearbox = {
	weight = 20,
	shouldClose = "true",
	image = "elite_gearbox.png",
	name = "elite_gearbox",
	type = "item",
	label = "Elite Gear Box",
	useable = "true",
  },
 board = {
	weight = 20,
	shouldClose = "true",
	image = "board.png",
	name = "board",
	type = "item",
	label = "Board",
	useable = "true",
  },
 chip = {
	weight = 20,
	shouldClose = "true",
	image = "chip.png",
	name = "chip",
	type = "item",
	label = "Chip",
	useable = "true",
  },
 elite_airfilter = {
	weight = 20,
	shouldClose = "true",
	image = "elite_airfilter.png",
	name = "elite_airfilter",
	type = "item",
	label = "Elite Intake Air Filter",
	useable = "true",
  },
 steel = {
	weight = 20,
	shouldClose = "true",
	image = "steel.png",
	name = "steel",
	type = "item",
	label = "Steel",
	useable = "true",
  },
 racing_connectingrods = {
	weight = 20,
	shouldClose = "true",
	image = "racing_connectingrods.png",
	name = "racing_connectingrods",
	type = "item",
	label = "Racing Connecting Rods Kit",
	useable = "true",
  },
 racing_block = {
	weight = 20,
	shouldClose = "true",
	image = "racing_block.png",
	name = "racing_block",
	type = "item",
	label = "Racing Block",
	useable = "true",
  },
 pro_suspension = {
	weight = 20,
	shouldClose = "true",
	image = "pro_suspension.png",
	name = "pro_suspension",
	type = "item",
	label = "Pro Suspension",
	useable = "true",
  },
 pro_brakes = {
	weight = 20,
	shouldClose = "true",
	image = "pro_brakes.png",
	name = "pro_brakes",
	type = "item",
	label = "Pro Brakes",
	useable = "true",
  },
 pro_block = {
	weight = 20,
	shouldClose = "true",
	image = "pro_block.png",
	name = "pro_block",
	type = "item",
	label = "Pro Block",
	useable = "true",
  },
 closerationgears = {
	weight = 20,
	shouldClose = "true",
	image = "closerationgears.png",
	name = "closerationgears",
	type = "item",
	label = "Close Ratio Gears",
	useable = "true",
  },
 pro_sparkplug = {
	weight = 20,
	shouldClose = "true",
	image = "pro_sparkplug.png",
	name = "pro_sparkplug",
	type = "item",
	label = "Pro Sparkplugs Kit",
	useable = "true",
  },
 street_tires = {
	weight = 20,
	shouldClose = "true",
	image = "street_tires.png",
	name = "street_tires",
	type = "item",
	label = "Street Tires",
	useable = "true",
  },
 bottle = {
	weight = 20,
	shouldClose = "true",
	image = "bottle.png",
	name = "bottle",
	type = "item",
	label = "Bottle",
	useable = "true",
  },
 ultimate_suspension = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_suspension.png",
	name = "ultimate_suspension",
	type = "item",
	label = "Ultimate Suspension",
	useable = "true",
  },
 engine_block = {
	weight = 20,
	shouldClose = "true",
	image = "engine_block.png",
	name = "engine_block",
	type = "item",
	label = "OEM Block",
	useable = "true",
  },
 esc = {
	weight = 20,
	shouldClose = "true",
	image = "esc.png",
	name = "esc",
	type = "item",
	label = "Stability Control System (ESC)",
	useable = "true",
  },
 ultimate_gearbox = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_gearbox.png",
	name = "ultimate_gearbox",
	type = "item",
	label = "Ultimate Gear Box",
	useable = "true",
  },
 racing_valves = {
	weight = 20,
	shouldClose = "true",
	image = "racing_valves.png",
	name = "racing_valves",
	type = "item",
	label = "Racing Head Valves Kit",
	useable = "true",
  },
 pro_crankshaft = {
	weight = 20,
	shouldClose = "true",
	image = "pro_crankshaft.png",
	name = "pro_crankshaft",
	type = "item",
	label = "Pro CrankShaft",
	useable = "true",
  },
 oem_suspension = {
	weight = 20,
	shouldClose = "true",
	image = "oem_suspension.png",
	name = "oem_suspension",
	type = "item",
	label = "OEM Suspension",
	useable = "true",
  },
 engine_oil = {
	weight = 20,
	shouldClose = "true",
	image = "engine_oil.png",
	name = "engine_oil",
	type = "item",
	label = "OEM Engine Oil",
	useable = "true",
  },
 abs = {
	weight = 20,
	shouldClose = "true",
	image = "abs.png",
	name = "abs",
	type = "item",
	label = "Anti-lock braking System",
	useable = "true",
  },
 racing_fuelinjector = {
	weight = 20,
	shouldClose = "true",
	image = "racing_fuelinjector.png",
	name = "racing_fuelinjector",
	type = "item",
	label = "Racing Fuel Injectors",
	useable = "true",
  },
 polyester = {
	weight = 20,
	shouldClose = "true",
	image = "polyester.png",
	name = "polyester",
	type = "item",
	label = "Polyester",
	useable = "true",
  },
 racing_oil = {
	weight = 20,
	shouldClose = "true",
	image = "racing_oil.png",
	name = "racing_oil",
	type = "item",
	label = "Racing Oil",
	useable = "true",
  },
 elite_valves = {
	weight = 20,
	shouldClose = "true",
	image = "elite_valves.png",
	name = "elite_valves",
	type = "item",
	label = "Elite Head Valves Kit",
	useable = "true",
  },
 racing_sparkplug = {
	weight = 20,
	shouldClose = "true",
	image = "racing_sparkplug.png",
	name = "racing_sparkplug",
	type = "item",
	label = "Racing Sparkplugs Kit",
	useable = "true",
  },
 engine_camshaft = {
	weight = 20,
	shouldClose = "true",
	image = "engine_camshaft.png",
	name = "engine_camshaft",
	type = "item",
	label = "OEM Camshaft",
	useable = "true",
  },
 ultimate_crankshaft = {
	weight = 20,
	shouldClose = "true",
	image = "ultimate_crankshaft.png",
	name = "ultimate_crankshaft",
	type = "item",
	label = "Ultimate CrankShaft",
	useable = "true",
  },
 sulfur = {
	weight = 20,
	shouldClose = "true",
	image = "sulfur.png",
	name = "sulfur",
	type = "item",
	label = "Sulfur",
	useable = "true",
  },